nelmio_api_doc:
    documentation:
        host: 127.0.0.1:8000
        schemes: [http, https]
        info:
            title: Test Oui car App
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        host_patterns:
            - ^api\.
